name: DevSecOps Pipeline

on: [push]

jobs:
  git-secrets:
    uses: ./.github/workflows/secrets.yml
    secrets: inherit
  snyk:
    needs: [git-secrets]
    uses: ./.github/workflows/snyk.yml
    secrets: inherit
  deploy:
    needs: [snyk]
    uses: ./.github/workflows/deploy-k8s.yml
    secrets: inherit
  dast:
    needs: [deploy]
    uses: ./.github/workflows/owasp-zap.yml
    secrets: inherit
