# name: Git Secrets

# on: [workflow_call]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           repository: awslabs/git-secrets

#       - name: Set up python environment
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"

#       - name: Install git secret
#         run: sudo make install

#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Scan the secrets with Talisman
#         uses: carhartl/talisman-secrets-scan-action@v1.4.0

#       - name: Run git-secrets
#         run: |
#           git secrets --install
#           git secrets --register-aws
#           git secrets --scan --recursive

#       # - name: Sending a message to the Slack channel when the process fails
#       #   uses: slackapi/slack-github-action@v1.24.0
#       #   with:
#       #     channel-id: ${{ secrets.CHANNEL_ID }}
#       #     payload: |
#       #       {
#       #           "text": "GitHub Action Pipeline Failed",
#       #           "blocks": [
#       #               {
#       #                   "type": "header",
#       #                   "text": {
#       #                       "type": "plain_text",
#       #                       "text": ":exclamation: GitHub Action Pipeline Failed :exclamation:",
#       #                       "emoji": true
#       #                   }
#       #               },
#       #               {
#       #                   "type": "divider"
#       #               },
#       #               {
#       #                   "type": "section",
#       #                   "fields": [
#       #                       {
#       #                           "type": "mrkdwn",
#       #                           "text": "*Status:*\n:x: ${{ job.status }}"
#       #                       },
#       #                       {
#       #                           "type": "mrkdwn",
#       #                           "text": "*User Commit:*\n${{ github.actor }}"
#       #                       },
#       #                       {
#       #                           "type": "mrkdwn",
#       #                           "text": "*Commit ID:*\n${{ github.sha }}"
#       #                       },
#       #                       {
#       #                         "type": "mrkdwn",
#       #                         "text": "*Job Name:*\nSECRETS"
#       #                       }
#       #                   ]
#       #               },
#       #               {
#       #                   "type": "section",
#       #                   "text": {
#       #                       "type": "mrkdwn",
#       #                       "text": "*:mag: More Information:*\nThe pipeline failed during the testing phase. Please review the logs for more details."
#       #                   }
#       #               },
#       #               {
#       #                   "type": "section",
#       #                   "text": {
#       #                       "type": "mrkdwn",
#       #                       "text": "<https://github.com/tinhtq/cicdpipeline/actions/runs/${{ github.run_id }}>"
#       #                   }
#       #               }
#       #           ]
#       #       }
#       #   env:
#       #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#       #   if: failure()
